# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('Ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auto_Blind', models.BooleanField(default=False)),
                ('auto_Ips', models.BooleanField(default=False)),
                ('auto_Light', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorName', models.CharField(max_length=30)),
                ('Pin1', models.IntegerField()),
                ('Pin2', models.IntegerField()),
                ('Pin3', models.IntegerField()),
                ('Pin4', models.IntegerField()),
                ('Ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Raspberry')),
            ],
        ),
    ]
