# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Pin1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='Pin2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='Pin3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='Pin4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
