# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20170520_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='moduleNum',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
